### ISSUE TITLE
How to choose T0 and T1 in effect_inference for continuous treatment variable [Question]

### ISSUE THREAD

**Issue by yuxinchenNU** [py-why/EconML#643]
Any insights on the following question would be much appreciated!

Say my control is treatment variable taking values from an interval between 1 and 5 continuously and my treatment takes values between 6 to 10 continuously. How should I choose the inputs T0 and T1 to obtain the CATE comparing the control and treatment? If I were to take a list of values for T0 and T1, would it suffice to take a list of values between 1 and 5 for T0 and a list of values between 6 and 10? And interpret the results as the treatment effect for higher (6 to 10) treatment variable vs the lower (1 to 5) value treatment variable?

I'm also confused about how T0 and T1 are selected in this [example notebook](https://github.com/microsoft/EconML/blob/main/notebooks/Causal%20Forest%20and%20Orthogonal%20Random%20Forest%20Examples.ipynb) for continuous treatment variable. In cell 9, effect_inference takes default values of T0 at 0 and T1 at 1. How do I interpret this for this case? Are the results comparing treatment variable taking the value of 1 vs 0?

**Comment by kbattocchi** [comment]
What does it mean for your control to have multiple values?  For continuous data we're estimating an effect which is linear in the treatment, so a treatment of 0 will be a true control that will not affect the output, while a treatment of value 2 will have twice the impact on the outcome that a treatment of value 1 has.  It's fine for your actual observed treatments to have any range of values (we do not need to observe actual treatments of value 0 as long as the effect really is linear in T and that there is sufficient variation in the values of T to identify the effect).  The marginal effect that we estimate is based on an increase in T of one unit (whatever that means for your setting), but when using the effect_inference method you can specify that you want the counterfactual effect of going from any starting treatment value T0 of your choice to any other treatment value T1 of your choice; because the effect is assumed to be linear this is just (T1-T0) times the marginal effect. Does that help?

**Comment by yuxinchenNU** [comment]
Thank you! This is very helpful!
