### ISSUE TITLE
W and X in documentation, what are the difference?

### ISSUE THREAD

**Issue by xiaogangzhu** [py-why/EconML#796]
Hi,

I have read the problem setting in documentation and we have controls W and X. I don't know what is the difference between them and how should I set it up when I am trying to fit a model, i.e. 
est = LinearDML()
est.fit(y, T, X=X, W=W)

can someone helps?

**Comment by kbattocchi** [comment]
The distinction is somewhat subtle - the difference is that only variables in X are used to calculate the heterogeneous treatment effect strength \theta(X).  So you will need to decide how you want to partition your confounders between controls W that potentially affect T and Y but not the strength of the treatment effect, and features X that affect T and Y and can also affect the strength of their relationship.

As one example, if you put everything into W instead of X (and just pass None for X), then will end up calculating the average treatment effect rather than a heterogeneous treatment effect.  At the other extreme, if you put everything into X and pass None for W, you are saying that the treatment effect can vary depending on every variable.

The more things you put into X instead of W, the more flexible your model is, but the harder the estimation problem becomes, and so you should expect your estimates to be noisier.

If the ultimate goal of your estimation task is to come up with an individualized policy, it may also be the case that there are certain variables that you don't want to consider as policy-relevant (e.g. maybe you are legally prohibited from using, say, gender to generate different treatment policies), in which case it may make sense to leave those in W instead of X even if you think that they may change the effect.

**Comment by xiaogangzhu** [comment]
Really detailed explain! Thanks!
