### ISSUE TITLE
Calculate ATE when T is continuous in double machine learning

### ISSUE THREAD

**Issue by xiaogangzhu** [py-why/EconML#797]
Hi all, 

I am trying to estimate ATE when T is continuous and also Y is continuous, I noticed double machine learning notebook demonstrated how to calculate treatment effect when there is a X fit in the model and output this kind of plot: 
![Screenshot from 2023-07-27 23-14-14](https://github.com/py-why/EconML/assets/65101307/4ebea53f-95b8-4b4f-8c4e-2aecb8265e52)
the code is something like
```
est = LinearDML(model_y=RandomForestRegressor(),
                model_t=RandomForestRegressor(),
                random_state=123)
est.fit(Y_train, T_train, X=X_train, W=W_train)
te_pred = est.effect(X_test)
```
However, i don't want any X fit in the model. My goal is to measure what is the treatment effect of different T on Y(You can simply think my goal is to replace x with T in the plot). The treatment effect of T on Y may not be linear, how can I achieve this? 

By the way, for method of est.effect(X,T0,T1)
```
T0 ((m, d_t) matrix or vector of length m, default 0) – Base treatments for each sample
T1 ((m, d_t) matrix or vector of length m, default 1) – Target treatments for each sample
```
I am very confused about base treatments and target treatments and don't know how to set this two parameters up. Can someone explains more clearly? 

Thanks!

**Comment by kbattocchi** [comment]
LinearDML (and most of our other estimators) assume that the effect is linear in (a featurization of) the treatment T. 

`effect(X, T0, T1)` will give you the effect (change in output) given covariates X of moving treatment assignment from T0 to T1.  
If you don't featurize the treatment and have a single treatment, then `effect(X, T0, T1)` will be linear in `T1-T0`, so just using `T0=0` and `T1=1` is sufficient to compute the result for any other pair of treatments (since `effect(X, T0, T1) == (T1-T0) * effect(X, 0, 1)`).

If you want to calculate a non-linear treatment effect, then the easiest way to do that is by using a treatment featurizer, which will expand the treatment you provide into multiple treatment columns - see [this notebook](../blob/main/notebooks/Treatment%20Featurization%20Examples.ipynb) for examples.

**Comment by xiaogangzhu** [comment]
My treatment is continuous and ranged from 0 to 80000, is that mean I need to set T0 = 0 and T1=80000 to get the ATE?

**Comment by kbattocchi** [comment]
In the case of continuous treatments there isn't a single ATE, there is (in general) an average treatment effect for each pair of source and target treatments, saying how the output would change on average if instead of treating everyone at level T0 you treat them at level T1.  For linear models, this is just some factor times T1-T0, but for non-linear effects that's not necessarily true.

So in your case if you want to know how the average effect of moving from one extreme to the other, you could use `effect(X=None, T0=0, T1=80000)`, but it really depends on exactly what you're trying to do (and if you use a treatment featurizer to model non-linear treatment effects, then it may not be the case that maximal treatment effect is achieved at the maximum treatment level, for example).

**Comment by xiaogangzhu** [comment]
Thanks!
