### ISSUE TITLE
criterion in grf.CausalForest

### ISSUE THREAD

**Issue by hila-de-moon** [py-why/EconML#904]
Hi,

Is their any chance of passing my own criterion function to measure the quality of a split?
I want to adjust the "het" option a bit.

Thank you in advance!

**Comment by vsyrgkanis** [comment]
Unfortunately no because this logic is written in Cython.

you’ll have to fork the library and change the logic in this file to whatever you want to implement and then reinstall econml from your fork. Note that this is a cython file and so you need to respect the cython language semantics.
https://github.com/py-why/EconML/blob/main/econml/grf/_criterion.pyx
